name: note
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  fluentui_icons: ^1.0.0
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  google_fonts: ^6.3.3
  gap: ^3.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    [assets/images/]
